---
title: "Introduction to the R language"
author: "Cyril Dourthe"
date: "`r Sys.Date()`"
output: html_document
---
<style>
details > summary {
  padding: 4px;
  width: 400px;
  background-color: #eeeeee;
  border: none;
  box-shadow: 1px 1px 2px #bbbbbb;
  cursor: pointer;
}
​
details > p {
  background-color: #E0F8EC;
  padding: 4px;
  margin: 0;
  box-shadow: 1px 1px 2px #bbbbbb;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Presentation

## Goal of this course

During this course, you'll get an introduction to the R language and its graphical interface named RStudio.
You'll learn how to use the language and its interface through various exercises.

The aim is to enable you to acquire basic programming skills in R, so that you can manipulate data tables, dissect them and extract the relevant information you need.

In this course, you'll also learn how to make simple but important graphical representations in biology. You'll see how to make them aesthetically pleasing and easy to read, so that you can use them in your publications.

## What is a programming language ?

A programming language is a language that your computer can "talk" and understand. It is like a set of instructions you give to the computer that he can execute.

As with any human language, there are syntactic rules to be observed. If the rules aren't followed, the computer won't understand the instructions.
If the list of instructions contains no errors and is clearly understandable by the computer, then it executes the order and returns a result. This can be the result of arithmetic operations, graphical representations, tables...

## What is R ?

R is a programming language designed specifically for working with data in different fields (biology, ecology, economy, financial...). It helps you analyze, visualize, and make sense of data.

You need to see R as a powerful calculator combined with an artist's toolset to have enhanced visualisation of your data.
R is a toolbox filled with plenty of already existing functionalities just waiting to be used.
It is very flexible and can be used for many different types of data-related tasks, from basic calculations to advanced machine learning.

This language is one of the most popular for data science and statistics. It's widely used in academia, research, and industry.
The big plus is that it's totally free-to-use with a very active community that already provides several thousand of extensions. You can interact with them in numerous forums and conferences.

You can download R here : https://cran.biotools.fr/

## R interface

R has a basic interface: the console.
This element is important because this is the tool to interact with the R programming language. It’s a command-line tool, meaning you type commands and see results immediately.
The interface is somewhat austere and doesn't offer many clickable buttons, just a field for writing command lines.

But luckily there's an interface designed for R that's much more friendly and intuitive!

## RStudio

RStudio is an Integrated Development Environment (IDE) for R. It's a much more powerful and user-friendly interface that makes working with R easier.

This interface features a number of clickable buttons and drop-down menus, making R easier to use and avoiding (sometimes) the need for command lines (which we'll look at later in this course).

You'll notice that the interface is divided into several panels. Those panels have a specific purpose, making it easier to manage every aspects of your work in R :

* Console: this is the panel with which you interact with R. As we saw earlier, it's this element that enables R to interpret your commands and respond to them.
* Environment/History: In this section, you'll see the results of some of your orders, which we'll explain in greater detail later in the course.
* Files/Plots/Packages/Help/Viewer
  - Files : This is basically a file browser. You can open files, manage your project directory, or set your working directory here.
  - Plots : It displays the visual output (graphs, charts, plots) generated by your R code. Each time you create a plot, it appears here. You can export or zoom in on these plots.
  - Packages : This is a list of all R packages installed on your system, showing which are currently loaded. You can install new packages, update existing ones, and load or unload packages for your session. (See further in the course)
  - Help : This is a help browser where you can look up R functions, packages, and documentation. It provides detailed documentation and examples for R functions and packages, making it easier to learn and troubleshoot. (See further in the course)
  - Viewer : It displays HTML outputs, such as web pages generated by R scripts or R Markdown documents. Useful for previewing reports, or other dynamic content within RStudio. (We won't detailed much this part)
  
